//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountTaction
    {
        public int id { get; set; }
        public System.DateTime Dt { get; set; }
        public int EntityId { get; set; }
        public int EntityTypeId { get; set; }
        public int Unit { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public int PaymentMethodId { get; set; }
    
        public virtual BankEntity Bank_Entity { get; set; }
        public virtual BankAccountTactionType Bank_AccountTactionType { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
