//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankFundType
    {
        public int id { get; set; }
        public string Title { get; set; }
        public int EntityTypeId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual BankEntityType Bank_EntityType { get; set; }
    }
}
