//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTaction
    {
        public int id { get; set; }
        public System.DateTime Dt { get; set; }
        public int PaymentMethodId { get; set; }
        public decimal AvailableBalance { get; set; }
        public decimal TotalExpenses { get; set; }
        public decimal TotalDeposit { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
