//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyMovement
    {
        public int id { get; set; }
        public System.DateTime dt { get; set; }
        public int ShopId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public decimal AmountOf { get; set; }
        public decimal AmountTo { get; set; }
        public decimal Rate { get; set; }
    }
}
