//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSubTypeDetails
    {
        public int id { get; set; }
        public int ItemId { get; set; }
        public int ItemSubTypeId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemSubType ItemSubType { get; set; }
    }
}
