//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class scope_info
    {
        public string sync_scope_name { get; set; }
        public string sync_scope_schema { get; set; }
        public string sync_scope_setup { get; set; }
        public string sync_scope_version { get; set; }
        public Nullable<long> sync_scope_last_clean_timestamp { get; set; }
        public string sync_scope_properties { get; set; }
    }
}
