//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class scope_info_client
    {
        public System.Guid sync_scope_id { get; set; }
        public string sync_scope_name { get; set; }
        public string sync_scope_hash { get; set; }
        public string sync_scope_parameters { get; set; }
        public Nullable<long> scope_last_sync_timestamp { get; set; }
        public Nullable<long> scope_last_server_sync_timestamp { get; set; }
        public Nullable<long> scope_last_sync_duration { get; set; }
        public Nullable<System.DateTime> scope_last_sync { get; set; }
        public string sync_scope_errors { get; set; }
        public string sync_scope_properties { get; set; }
    }
}
