//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Taction = new HashSet<Taction>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int GroupId { get; set; }
        public string Nickname { get; set; }
        public string No { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
    
        public virtual ShopGroup ShopGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taction> Taction { get; set; }
    }
}
