//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceManager_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public int id { get; set; }
        public int userId { get; set; }
        public byte[] imageData { get; set; }
        public bool isDefault { get; set; }
    
        public virtual User User { get; set; }
    }
}
